# [Strawgolem Config]

# [Golem Health]
# The max health of a golem.
Max Health=6.0
# The max health of a barrel.
Barrel Max Health=100
# Whether a golem should have hunger.
Hunger=false
# The time in seconds it takes for a Straw Golem to become fully hungry.
Hunger Time=4800
# The item(s) a golem is fed with.
Food Item=minecraft:apple
# Whether a golem should have a lifespan.
Lifespan=false
# The time in seconds that a Straw Golem will have as a natural lifespan in a default environment.
Lifespan Time=4800
# Whether golems should have variation in their lifespans.
Lifespan Variation=true
# Whether a golem should age faster or slower in response to environmental factors, examples being:
# A golem in rain or water will age faster, whereas a golem in cold biomes will age slower.
Environmental Decay=false
# The item(s) a golem is repaired with.
Repair Item=minecraft:wheat
# Whether a golem should shiver in response to environmental factors such as rain and cold biomes.
Shiver=true
# [Golem Movement]
# The walk speed of a golem.
Walk Speed=0.5
# The run speed of a golem.
Run Speed=0.8
# How far a golem can wander
Wander Range=24
# Whether a golem should panic when threatened.
Panic=true
# How far a golem can flee
Flee Range=15.0
# [Golem Harvesting]
# Range for a golem to detect crops and chests.
Harvest Range=24
# Whether a golem should harvest crop blocks like pumpkins and melons.
Block Harvesting=true
# Whether a golem should only harvest crops in the whitelist.
Use Whitelist=false
# What crops should be harvested, please use valid resource locations.
Crop Whitelist= 
# [Miscellaneous]
# Whether animals should try to attack Straw Golems
Hungry Animals=true
# Whether pillagers should try to attack Straw Golems
Angry Pillagers=true
# Whether the Straw Golem winter skin will be shown.
# Note: The skin is still only attainable during the Winter.
Winter Skin=true
# For determining season-based timings. Acceptable values are: North, South, None.
# Note: None will disable seasonal events.
Hemisphere=North
# [Metadata]
# Please do not modify this value casually, or risk config values being overwritten or made invalid!
Config Version Number=1

